# NumPy

**NumPy** é uma biblioteca de algebra linear.
Ela importante para _Data Science_ em **Python** pois as próximas bibliotecas a utilizam como um de seus blocos principais.

Outro motivo é porque também é muito rápida em execução e permite a criação de _arrays_ homogêneos.

In [1]:
# Comumente importada com essa abreviação
import numpy as np

## NumPy _Arrays_

NumPy _arrays_ serão altamente vistos e trabalhados

In [2]:
np.array?

Docstring:
array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) unless 'F' is
    specified, in which case it will be in Fortran order (column major).
    If

In [3]:
py_list = [1, 2, 3]
py_list, type(py_list)

([1, 2, 3], list)

In [4]:
np_arr = np.array(py_list)
np_arr, type(np_arr)

(array([1, 2, 3]), numpy.ndarray)

### outros métodos

NumPy possui outros métodos capazes de gerar arrays.

In [5]:
# Semelhante à função range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# Gera um array com as dimensões passadas como argumento 
print(np.zeros((2, 3)))
print('\n')
print(np.ones((3, 2)))

[[0. 0. 0.]
 [0. 0. 0.]]


[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
# Retorna um array de 'num' números igualmente espaçados entre 'start' e 'stop'
np.linspace(0, 9, 10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [8]:
# Retorna uma matriz com 1 na diagonal e 0 nas demais posições
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])