# Random

NumPy possui diversas formas de criar arrays com números aleatórios.

In [1]:
import numpy as np

In [2]:
# Retorna um array com as dimensões passadas como parâmetro com números aleatórios entre [0, 1)
np.random.rand(2, 3)

array([[0.58098081, 0.91022123, 0.53946225],
       [0.95413108, 0.25887835, 0.20777074]])

In [3]:
# Retorna um array com as dimensões passadas como parâmetro com números aleatórios de uma distribuição normal centrada em 0
np.random.randn(3, 2)

array([[0.33040019, 0.36360988],
       [0.58237381, 0.9582118 ],
       [0.42020667, 0.63040295]])

In [4]:
# Retorna um array de inteiros dentro do intervalo ['low', 'high') com as dimensões passadas como parâmetro
np.random.randint(
    low=0,
    high=50,
    size=(2, 4)
)

array([[12, 27, 10, 12],
       [28, 38, 28, 24]])

# Array Methods

In [5]:
np_arr = np.random.randint(0, 50, 12)
np_arr

array([36, 43,  8, 30, 32, 18,  4, 33,  2, 16, 31, 27])

In [6]:
# reshape: muda as dimensões do array, porém deve conter o mesmo número de elementos
np_mat = np_arr.reshape((3, 4))
np_mat

array([[36, 43,  8, 30],
       [32, 18,  4, 33],
       [ 2, 16, 31, 27]])

In [7]:
# Metrics - Retorna:
maximum = np_arr.max()      # maximo valor do array
max_loc = np_arr.argmax()   # índice do maximo
minimum = np_arr.min()      # mínimo valor do array
min_loc = np_arr.argmin()   # índice do mínimo

mean = np_arr.mean()        # média aritmética dos valores do array
std = np_arr.std()          # desvio padrão dos valores do array
soma = np_arr.sum()         # soma dos valores do array

print(f'''
maximum: {maximum};
max at: index {max_loc};
minimum: {minimum};
min at: index {min_loc};
mean: {mean};
std: {std};
sum: {soma};
shape: {np_arr.shape};
data type: {np_arr.dtype}
''')


maximum: 43;
max at: index 1;
minimum: 2;
min at: index 8;
mean: 23.333333333333332;
std: 12.840906856172149;
sum: 280;
shape: (12,);
data type: int64

