# Indexing and Selection

Formas de acessar um ou multiplos elementos de um array.

In [1]:
import numpy as np

In [2]:
array = np.arange(1, 11)
array, type(array)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), numpy.ndarray)

Assim como nas listas, elementos individuais de um array são acessados com a mesma notação.

E o mesmo vale caso seja selecionado uma "fatia" do array.

In [3]:
array[3], array[2:5]

(4, array([3, 4, 5]))

## Broadcasting

É possível atribuir um valor para multiplas posições de um array.

In [4]:
# Atribuindo 10 para os ultimos 5 elementos do array
array[6:] = 10
array

array([ 1,  2,  3,  4,  5,  6, 10, 10, 10, 10])

## Atribuição

Para evitar problemas com memória, atribuir partes de um array para outra variável é feita por referência, então alterar uma refletirá na outra. para evitar isso, utiliza-se o método `copy`.

In [5]:
# Atribuição por referência
slice_of_array = array[2:8]
slice_of_array

array([ 3,  4,  5,  6, 10, 10])

In [6]:
slice_of_array[2:4]

array([5, 6])

In [7]:
slice_of_array[2:4] = 42
slice_of_array

array([ 3,  4, 42, 42, 10, 10])

In [8]:
array

array([ 1,  2,  3,  4, 42, 42, 10, 10, 10, 10])

In [9]:
copy_of_array = array.copy()

copy_of_array[2:8] = 24

copy_of_array

array([ 1,  2, 24, 24, 24, 24, 24, 24, 10, 10])

In [10]:
array

array([ 1,  2,  3,  4, 42, 42, 10, 10, 10, 10])

In [11]:
matrix = np.array([[0, 5, 10],[15, 20, 25],[30, 35, 40]])
matrix

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [12]:
# Acessando elemento com 2 colchetes
matrix[1][2]

25

In [13]:
# Acessando elemento com 1 colchete
matrix[1, 2]

25

In [14]:
# Selecionando um pedaço da matrix
matrix[1: , :2]

array([[15, 20],
       [30, 35]])

# Conditional Selection

Ao se usar um array como operando de uma operação relacional, será retornado um array com o resultado da operação aplicado a cada elemento. O mesmo vale para as demais operações.

Ao passar esse resultado entre colchetes, será retornado os elementos de cujo o índice corresponde a verdadeiro.

In [15]:
new_array = np.arange(0, 10)
new_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
bool_array = 5 > new_array
bool_array

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [17]:
new_array[bool_array]

array([0, 1, 2, 3, 4])

In [18]:
new_array[(new_array % 2) == 0]

array([0, 2, 4, 6, 8])