# Operations

## Operações com arrays de mesma forma

O array resultante possui a mesma forma e em cada posição o resultado da operação envolvendo os valores que estavam na mesma posição em cada array.

In [1]:
import numpy as np

In [2]:
array1, array2 = np.arange(0, 5), np.arange(5, 10)
array1, array2

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [3]:
# Soma
array1 + array2

array([ 5,  7,  9, 11, 13])

In [4]:
# Subtração
array1 - array2

array([-5, -5, -5, -5, -5])

In [5]:
# Multiplicação
array1 * array2

array([ 0,  6, 14, 24, 36])

In [6]:
# Divisão
array1 / array2

array([0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444])

In [7]:
# Divisão inteira
array1 // array2

array([0, 0, 0, 0, 0])

In [8]:
# Módulo
array1 % array2

array([0, 1, 2, 3, 4])

In [9]:
# Exponenciação
array1 ** array2

array([     0,      1,    128,   6561, 262144])

## Operações com apenas uma escalar

O array resultante possui possui a mesma forma que o array inicial e em cada posição o resultado da operação entre o valor na posição e a escalar.

In [10]:
array1 * 42

array([  0,  42,  84, 126, 168])

# Métodos interessantes

In [11]:
# Retorna um array com a raiz quadrada de cada elemento
np.sqrt(array1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [12]:
# Retorna um array com 'e' elevado a cada elemento
np.exp(array1)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])